apiVersion: v1
kind: Service
metadata:
  name: load-balancer
spec:
  selector:
    app: nodejs
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rearaoke-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: rearaoke
        image: nmarklund10/rearaoke:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always