apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-rearaoke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: rearaoke
        image: nmarklund10/rearaoke:<TAG>
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
      strategy:
        type: Recreate