apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rearaoke
  region: <REGION>

nodeGroups:
  - name: blue
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 20
  - name: green
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 20
