apiVersion: apps/v1
kind: Deployment
metadata:
  name: <ID>-rearaoke-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <ID>
  template:
    metadata:
      labels:
        app: <ID>
    spec:
      containers:
      - name: rearaoke
        image: nmarklund10/rearaoke:<TAG>
        ports:
        - containerPort: 3000
        imagePullPolicy: Always