---
- name: Install dependencies
  become: yes
  apt:
    name: [ca-certificates, curl, gnupg, lsb-release, net-tools]
- name: Add docker GPG key
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
- name: set up stable repository
  become: yes
  shell: >
    echo
    "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
- name: install docker engine
  become: yes
  apt:
    name: [docker-ce, docker-ce-cli, containerd.io]
    state: latest
    update_cache: yes
- name: add user to docker group
  become: yes
  user:
    name: ubuntu
    groups: [docker]
    append: yes
- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection
- name: copy docker daemon.json file
  become: yes
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
- name: restart docker service
  become: yes
  shell: systemctl restart docker